---
- hosts: all
  user: vagrant
  sudo: yes
  vars_files: 
    - vars.yml
  tasks:
    - name: configure /etc/motd
      template: src=motd.j2 dest=/etc/motd

    - name: install ifenslave
      apt: name=ifenslave state=present

    - name: install vlan
      apt: name=vlan state=present

    - name: adding bonding and rtc modules to /etc/modules
      lineinfile: dest=/etc/modules line="{{ item }}"
      with_items: 
        - "rtc"
        - "bonding" 
        - "8021q"

    - name: push hypervisors public SSH key
      # If Linux
      # authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      # authorized_key: user=vagrant key="{{ lookup('file', '/home/slaffer/.ssh/id_rsa.pub') }}"
      #
      # If Mac
      authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"    
      # authorized_key: user=vagrant key="{{ lookup('file', '/Users/slaffer/.ssh/id_rsa.pub') }}"    

#    - name: install CumulusLinux-2.5 apt key
#      copy: src=CumulusLinux-2.5.gpg dest=/home/vagrant/CumulusLinux-2.5.gpg
#
#    - name: Ensure Cumulus Linux apt-key is installed
#      apt_key: file=/home/vagrant/CumulusLinux-2.5.gpg state=present
#      sudo: yes

